#!/usr/bin/env bash
# This script transfers a file from a local machine to a server

if [ $# -lt 3 ]
then
    echo Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY
elif [ $# -lt 4 ]
then
    # Giving meaningful names to the script arguments
    file_path=$1 ; server_ip=$2 ; user_name=$3 ; dest=~/
    scp -o StrictHostKeyChecking=no "$file_path" "$user_name"@"$server_ip":"$dest"
else
    # Giving meaningful names to the script arguments
    file_path=$1 ; server_ip=$2 ; user_name=$3 ; id_rsa=$4
    scp -i "$id_rsa" -o StrictHostKeyChecking=no "$file_path" "$user_name"@"$server_ip":"$dest"
fi
