#!/usr/bin/env bash
# This script configure an nginx server so that
# /redirect_me is redirecting to another page

redirection="\tserver_name _;\n\n\tlocation \/redirect_me {\n\t\treturn 301 https:\/\/github.com\/fabeklou;\n\t}\n"
config_file=/etc/nginx/sites-available/default

apt update -y ; apt upgrade -y
apt install nginx -y
ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.html
sudo sed -i "s/server_name _;/${redirection}/" "$config_file"
service nginx restart
