#!/usr/bin/env bash
# This script Configure Nginx so that its HTTP response contains a custom header (on web-01 and web-02)

redirection="server_name _;\n\n\tlocation \/redirect_me {\n\t\treturn 301 https:\/\/github.com\/fabeklou;\n\t}\n"
not_found="server_name _;\n\terror_page 404 \/404.html;\n\tlocation \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}\n"
config_file=/etc/nginx/sites-available/default
served_by="server_name _;\n\tadd_header X-Served-By $HOSTNAME;"

apt update -y ; apt upgrade -y
apt install nginx -y
ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.html
echo Ceci n\'est pas une page > /var/www/html/404.html
sudo sed -i "s/server_name _;/${redirection}/" "$config_file"
sudo sed -i "s/server_name _;/${not_found}/" "$config_file"
sudo sed -i "s/server_name _;/${served_by}/" "$config_file"
service nginx restart
