#!/usr/bin/env bash
# This script Configure HAproxy so that it send traffic to
# web-01 and web-02
# Distribute requests using a roundrobin algorithm

apt update -y ; apt upgrade -y

# Enabling a dedicated PPA
# apt-get install --no-install-recommends software-properties-common
# add-apt-repository ppa:vbernat/haproxy-2.8

# Installing HAProxy
apt-get install haproxy -y

# Changing the value of ENABLED to 1 to enable the HAProxy init scrip
echo "ENABLED=1" | tee -a /etc/default/haproxy

# haproxy config
config=\
"
frontend fabeklou-frontend
    bind *:80
    mode http
    default_backend fabeklou-backend

backend fabeklou-backend
    balance roundrobin
    server 258961-web-01 18.234.169.238:80 check
    server 258961-web-02 35.174.176.187:80 check
"

# updating the haproxy.cfg file
echo "$config" | tee -a /etc/haproxy/haproxy.cfg

service haproxy restart
