#!/usr/bin/env bash
# This script pings en IP passed as en argument from the terminal

IP_ADD=$1

if [ "$IP_ADD" = '' ]
then
    echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
    exit 1
fi

ping -c 5 "$IP_ADD"
