#!/usr/bin/env bash
# This script displays `Best School` 10 times

FROM=0 ; MAX=10

while [ $FROM -lt $MAX ]
do
    if [ $FROM -eq 3 ]
    then
        echo "bad luck"
    elif [ $FROM -eq 7 ]
    then
        echo "good luck"
    else
        echo "Best School"
    fi
    ((FROM++))
done
