#!/usr/bin/env bash
# This script gives you information about the school file
# https://www.geeksforgeeks.org/bash-scripting-how-to-check-if-file-exists/

FILE="school"

if [ -e $FILE ]
then
    echo "school file exists"
    
    if [ -s $FILE ]
    then
        echo "school file is not empty"
    else
        echo "school file is empty"
    fi

    if [ -f $FILE ]
    then
        echo "school is a regular file"
    fi

else
    echo "school file does not exist"
fi
